# https://taskfile.dev

version: "3"

vars:
  GREETING: |-
    Usage: task {setup-toos,resolve-deps,build}

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true

  setup-tools: |
    task -d vault {{.TASK}}

  resolve-deps: |
    task -d vault {{.TASK}}

  clean: |
    task -d vault {{.TASK}}

  build:
    desc: build all
    deps:
      - task: resolve-deps
    cmds:
      - task -d vault build-site {{.watch}}
      


    
  watch-build:
    desc: build all
    deps:
      - task: resolve-deps
    cmds:
      - task -d vault build-site-cmd --watch
      
  serve-build:
    desc: expose as http
    cmds:
    - task -d vault serve-site