# https://taskfile.dev

version: "3"

vars:
  GREETING: |-
    Usage: task {setup-toos,resolve-deps,build}

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -a
      - task -l
    silent: true

  setup-tools: |
    which npx || npm install -g npx yarn
    which dendron-cli || npm install @dendronhq/dendron-cli@latest

  resolve-deps: |
    pwd
    ls ../.next || npx dendron publish init

  build-site-cmd: |-
    npx dendron publish build
    npx dendron publish export

  build-site:
    desc: build dendron html static site
    deps:
      - task: resolve-deps
    cmds:
      - task: build-site-cmd
    sources:
      - ./*.md
      - ./*.yaml
      - ./*.yml
      - ./*.png
    generates:
      - ../.next/out/**/*.html
      - ../.next/out/**/*.png

  serve-site: |
    pushd ../.next/out
      python -m http.server 17333
    popd
