# https://taskfile.dev

version: "3"

vars:
  GREETING: |-
    Usage: task {setup-toos,resolve-deps,build}

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -a
      - task -l
    silent: true

  setup-tools: |-
    cd ..
    which npx || npm install -g npx yarn
    which dendron-cli ||  bash -c ' \
      npm init -y \
      && npm install @dendronhq/dendron-cli@latest \
      '

  resolve-deps: |-
    pwd

    ls ../.next || npx dendron publish init
  
  clean: |-
    rm -rf ../.next/out

  build-site-cmd:
    cmds:
      - cmd: |-
          npx dendron publish build
          npx dendron publish export
    sources:
      - ./*.md
      - ./*.yaml
      - ./*.yml
      - ./*.png
    generates:
      - ../.next/out/**/*.html
      - ../.next/out/**/*.png

  build-site:
    desc: build dendron html static site
    deps:
      - task: resolve-deps
    cmds:
      - task: build-site-cmd


  serve-site: |
    pushd ../.next/out
      python -m http.server 17333
    popd
